spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-batch
    username:
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        highlight_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

  batch:
    jdbc:
      initialize-schema: always # batch 시 초기 스키마를 설정 + @EnableBatchProcessing 은 없어야 함

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
      hibernate:
        orm:
          jdbc:
            bind: trace # 파라미터 값 나오게 하기. ver.spring boot 3